-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_user_profiles" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "gender" TEXT,
    "birthDate" DATETIME,
    "height" REAL,
    "weight" REAL,
    "targetWeight" REAL,
    "bodyFatPercentage" REAL,
    "leanMass" REAL,
    "fatMass" REAL,
    "waistCircumference" REAL,
    "hipCircumference" REAL,
    "neckCircumference" REAL,
    "bmr" REAL,
    "tdee" REAL,
    "bmi" REAL,
    "measuredBMR" REAL,
    "metabolicFactor" REAL,
    "healthStatus" TEXT,
    "isPregnant" BOOLEAN NOT NULL DEFAULT false,
    "pregnancyTrimester" INTEGER,
    "isLactating" BOOLEAN NOT NULL DEFAULT false,
    "lactationMonths" INTEGER,
    "activityLevel" TEXT,
    "exerciseType" TEXT,
    "exerciseFrequency" INTEGER,
    "exerciseMinutes" INTEGER,
    "exerciseIntensity" TEXT,
    "trainingGoal" TEXT,
    "workType" TEXT,
    "workHoursPerDay" INTEGER,
    "sleepHours" INTEGER,
    "sleepQuality" TEXT,
    "stressLevel" TEXT,
    "isSmoker" BOOLEAN NOT NULL DEFAULT false,
    "cigarettesPerDay" INTEGER,
    "alcoholConsumption" TEXT,
    "alcoholDrinksPerWeek" INTEGER,
    "goal" TEXT,
    "targetCalories" INTEGER,
    "calorieDeficit" INTEGER,
    "calorieSurplus" INTEGER,
    "weightChangeRate" TEXT,
    "targetBodyFat" REAL,
    "targetLeanMass" REAL,
    "targetWaist" REAL,
    "performanceGoals" TEXT,
    "mealsPerDay" INTEGER NOT NULL DEFAULT 3,
    "snacksPerDay" INTEGER NOT NULL DEFAULT 0,
    "intermittentFasting" TEXT,
    "fastingWindowStart" TEXT,
    "fastingWindowEnd" TEXT,
    "availableEquipments" TEXT NOT NULL DEFAULT '[]',
    "kitchenSize" TEXT,
    "cookingSkill" TEXT,
    "masteredTechniques" TEXT NOT NULL DEFAULT '[]',
    "hasMobilityIssues" BOOLEAN NOT NULL DEFAULT false,
    "physicalLimitations" TEXT,
    "needsCookingHelp" BOOLEAN NOT NULL DEFAULT false,
    "maxPrepTimePerMeal" INTEGER,
    "maxPrepTimePerDay" INTEGER,
    "breakfastPrepTime" INTEGER,
    "lunchPrepTime" INTEGER,
    "dinnerPrepTime" INTEGER,
    "snackPrepTime" INTEGER,
    "availableDays" TEXT NOT NULL DEFAULT '[]',
    "availableHours" TEXT,
    "mealPrepPreference" BOOLEAN NOT NULL DEFAULT false,
    "mealPrepDays" TEXT NOT NULL DEFAULT '[]',
    "budgetPerMeal" REAL,
    "budgetPerDay" REAL,
    "budgetPerWeek" REAL,
    "budgetPerMonth" REAL,
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "pricePreference" TEXT,
    "optimizeForCost" BOOLEAN NOT NULL DEFAULT false,
    "acceptCheaperAlternatives" BOOLEAN NOT NULL DEFAULT true,
    "preferredCookingMethods" TEXT NOT NULL DEFAULT '[]',
    "avoidedCookingMethods" TEXT NOT NULL DEFAULT '[]',
    "complexityPreference" TEXT,
    "maxSteps" INTEGER,
    "batchCooking" BOOLEAN NOT NULL DEFAULT false,
    "batchPortions" INTEGER,
    "storageDays" INTEGER,
    "acceptsFreezing" BOOLEAN NOT NULL DEFAULT true,
    "macroRatio" TEXT,
    "proteinTarget" REAL,
    "carbTarget" REAL,
    "fatTarget" REAL,
    "fiberTarget" REAL,
    "micronutrientFocus" TEXT NOT NULL DEFAULT '[]',
    "prefersWholeFoods" BOOLEAN NOT NULL DEFAULT false,
    "prefersOrganic" BOOLEAN NOT NULL DEFAULT false,
    "prefersMinimallyProcessed" BOOLEAN NOT NULL DEFAULT false,
    "takesSupplements" BOOLEAN NOT NULL DEFAULT false,
    "supplementsList" TEXT,
    "allergies" TEXT NOT NULL DEFAULT '[]',
    "allergySeverity" TEXT,
    "intolerances" TEXT NOT NULL DEFAULT '[]',
    "celiac" BOOLEAN NOT NULL DEFAULT false,
    "medicalConditions" TEXT NOT NULL DEFAULT '[]',
    "medications" TEXT,
    "medicationInteractions" TEXT,
    "sodiumLimit" INTEGER,
    "potassiumLimit" INTEGER,
    "phosphorusLimit" INTEGER,
    "proteinLimit" INTEGER,
    "fluidLimit" INTEGER,
    "fiberLimit" INTEGER,
    "recentSurgeries" TEXT,
    "postSurgeryRestrictions" TEXT,
    "hasGastricBypass" BOOLEAN NOT NULL DEFAULT false,
    "bypassType" TEXT,
    "otherProcedures" TEXT,
    "sweetPreference" TEXT,
    "sourPreference" TEXT,
    "saltyPreference" TEXT,
    "bitterPreference" TEXT,
    "umamiPreference" TEXT,
    "spicyPreference" TEXT,
    "spiceLevel" TEXT,
    "crispyPreference" TEXT,
    "creamyPreference" TEXT,
    "chewyPreference" TEXT,
    "softPreference" TEXT,
    "crunchyPreference" TEXT,
    "smoothPreference" TEXT,
    "temperaturePreference" TEXT,
    "likedFoods" TEXT NOT NULL DEFAULT '[]',
    "dislikedFoods" TEXT NOT NULL DEFAULT '[]',
    "neutralFoods" TEXT NOT NULL DEFAULT '[]',
    "mealHistory" TEXT NOT NULL DEFAULT '[]',
    "likedMeals" TEXT NOT NULL DEFAULT '[]',
    "dislikedMeals" TEXT NOT NULL DEFAULT '[]',
    "mealRatings" TEXT NOT NULL DEFAULT '{}',
    "mealNotes" TEXT NOT NULL DEFAULT '{}',
    "varietyPreference" TEXT,
    "evaluationFrequency" TEXT,
    "lastCalculated" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "user_profiles_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_user_profiles" ("acceptCheaperAlternatives", "acceptsFreezing", "activityLevel", "alcoholConsumption", "alcoholDrinksPerWeek", "availableDays", "availableEquipments", "availableHours", "avoidedCookingMethods", "batchCooking", "batchPortions", "birthDate", "bitterPreference", "bmi", "bmr", "bodyFatPercentage", "breakfastPrepTime", "budgetPerDay", "budgetPerMeal", "budgetPerMonth", "budgetPerWeek", "bypassType", "calorieDeficit", "calorieSurplus", "carbTarget", "chewyPreference", "cigarettesPerDay", "complexityPreference", "cookingSkill", "creamyPreference", "createdAt", "crispyPreference", "crunchyPreference", "currency", "dinnerPrepTime", "dislikedFoods", "dislikedMeals", "evaluationFrequency", "exerciseFrequency", "exerciseIntensity", "exerciseMinutes", "exerciseType", "fastingWindowEnd", "fastingWindowStart", "fatMass", "fatTarget", "fiberLimit", "fiberTarget", "fluidLimit", "gender", "goal", "hasGastricBypass", "hasMobilityIssues", "healthStatus", "height", "hipCircumference", "id", "intermittentFasting", "isLactating", "isPregnant", "isSmoker", "kitchenSize", "lactationMonths", "lastCalculated", "leanMass", "likedFoods", "likedMeals", "lunchPrepTime", "macroRatio", "masteredTechniques", "maxPrepTimePerDay", "maxPrepTimePerMeal", "maxSteps", "mealHistory", "mealNotes", "mealPrepDays", "mealPrepPreference", "mealRatings", "mealsPerDay", "measuredBMR", "medicalConditions", "medicationInteractions", "medications", "metabolicFactor", "micronutrientFocus", "neckCircumference", "needsCookingHelp", "neutralFoods", "optimizeForCost", "otherProcedures", "performanceGoals", "phosphorusLimit", "physicalLimitations", "postSurgeryRestrictions", "potassiumLimit", "preferredCookingMethods", "prefersMinimallyProcessed", "prefersOrganic", "prefersWholeFoods", "pregnancyTrimester", "pricePreference", "proteinLimit", "proteinTarget", "recentSurgeries", "saltyPreference", "sleepHours", "sleepQuality", "smoothPreference", "snackPrepTime", "snacksPerDay", "sodiumLimit", "softPreference", "sourPreference", "spiceLevel", "spicyPreference", "storageDays", "stressLevel", "supplementsList", "sweetPreference", "takesSupplements", "targetBodyFat", "targetCalories", "targetLeanMass", "targetWaist", "targetWeight", "tdee", "temperaturePreference", "trainingGoal", "umamiPreference", "updatedAt", "userId", "varietyPreference", "waistCircumference", "weight", "weightChangeRate", "workHoursPerDay", "workType") SELECT "acceptCheaperAlternatives", "acceptsFreezing", "activityLevel", "alcoholConsumption", "alcoholDrinksPerWeek", "availableDays", "availableEquipments", "availableHours", "avoidedCookingMethods", "batchCooking", "batchPortions", "birthDate", "bitterPreference", "bmi", "bmr", "bodyFatPercentage", "breakfastPrepTime", "budgetPerDay", "budgetPerMeal", "budgetPerMonth", "budgetPerWeek", "bypassType", "calorieDeficit", "calorieSurplus", "carbTarget", "chewyPreference", "cigarettesPerDay", "complexityPreference", "cookingSkill", "creamyPreference", "createdAt", "crispyPreference", "crunchyPreference", "currency", "dinnerPrepTime", "dislikedFoods", "dislikedMeals", "evaluationFrequency", "exerciseFrequency", "exerciseIntensity", "exerciseMinutes", "exerciseType", "fastingWindowEnd", "fastingWindowStart", "fatMass", "fatTarget", "fiberLimit", "fiberTarget", "fluidLimit", "gender", "goal", "hasGastricBypass", "hasMobilityIssues", "healthStatus", "height", "hipCircumference", "id", "intermittentFasting", "isLactating", "isPregnant", "isSmoker", "kitchenSize", "lactationMonths", "lastCalculated", "leanMass", "likedFoods", "likedMeals", "lunchPrepTime", "macroRatio", "masteredTechniques", "maxPrepTimePerDay", "maxPrepTimePerMeal", "maxSteps", "mealHistory", "mealNotes", "mealPrepDays", "mealPrepPreference", "mealRatings", "mealsPerDay", "measuredBMR", "medicalConditions", "medicationInteractions", "medications", "metabolicFactor", "micronutrientFocus", "neckCircumference", "needsCookingHelp", "neutralFoods", "optimizeForCost", "otherProcedures", "performanceGoals", "phosphorusLimit", "physicalLimitations", "postSurgeryRestrictions", "potassiumLimit", "preferredCookingMethods", "prefersMinimallyProcessed", "prefersOrganic", "prefersWholeFoods", "pregnancyTrimester", "pricePreference", "proteinLimit", "proteinTarget", "recentSurgeries", "saltyPreference", "sleepHours", "sleepQuality", "smoothPreference", "snackPrepTime", "snacksPerDay", "sodiumLimit", "softPreference", "sourPreference", "spiceLevel", "spicyPreference", "storageDays", "stressLevel", "supplementsList", "sweetPreference", "takesSupplements", "targetBodyFat", "targetCalories", "targetLeanMass", "targetWaist", "targetWeight", "tdee", "temperaturePreference", "trainingGoal", "umamiPreference", "updatedAt", "userId", "varietyPreference", "waistCircumference", "weight", "weightChangeRate", "workHoursPerDay", "workType" FROM "user_profiles";
DROP TABLE "user_profiles";
ALTER TABLE "new_user_profiles" RENAME TO "user_profiles";
CREATE UNIQUE INDEX "user_profiles_userId_key" ON "user_profiles"("userId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
